[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "optycal"
version = "0.1.0"
description = "A Python based physical optics simulator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "matplotlib>=3.8",
    "numba-progress>=1.1.3",
    "numba>=0.57.0",
    "numpy>=1.24",
    "pyvista>=0.45.3",
    "rich>=14.1.0",
    "scipy>=1.14.0",
    "shapely>=2.0.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist.sources]
"src/optycal"  = "optycal"

[dependency-groups]
dev = [
    "pipdeptree>=2.28.0",
    "pytest>=8.4.1",
    "scikit-umfpack>=0.4.2",
]

[tool.uv]
no-build-isolation-package = ["cchardet"]

[project.urls]
Homepage = "https://github.com/FennisRobert/Optycal"
Issues = "https://github.com/FennisRobert/Optycal/issues"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
publish-url = "https://upload.pypi.org/legacy"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple"
publish-url = "https://test.pypi.org/legacy"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--ignore=trial_scripts"
]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]